/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 8c196ba97ba2228b3cd62e64664cda91)
interface __BaseEnv_Env {
  DB: D1Database;
  ADMIN_X_USER_IDS: '1010812501611565056';
  X_CONSUMER_KEY: string;
  X_CONSUMER_SECRET: string;
  X_CLIENT_ID: string;
  X_CLIENT_SECRET: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./workers/app');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'ADMIN_X_USER_IDS'
      | 'X_CONSUMER_KEY'
      | 'X_CONSUMER_SECRET'
      | 'X_CLIENT_ID'
      | 'X_CLIENT_SECRET'
    >
  > {}
}
