/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a85ca5554d381189f43f8544c4a505e9)
interface __BaseEnv_Env {
  DB: D1Database;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./workers/app');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
